
default: &default
  main_state_id: 1
  document_root: /www/graveyards4/htdocs

  # a free form text name, used mainly for META
  site_name: graveyards.com
  
  # base url for canonical links - no trailing slash
  base_url: http://graveyards.com

  owner_name: Matt Hucke
  owner_email: hucke@cynico.net

  # Each of these must exist as a section in secrets.yml.
  auth_providers:
    # name: config hash
    facebook:
      :name: 'Facebook'
      :opts: 
    twitter:
      :name: 'Twitter'
      :opts: 
      #  :force_login: true
    google_oauth2:
      :name: 'Google'
      :icon_name: 'google'
    #pinterest:
    #  :name: 'Pinterest'

development: &development
  <<: *default

test:
  <<: *development

production:
  <<: *default

