
default: &default
  main_state_id: 1
  document_root: /www/graveyards4/htdocs
  site_name: graveyards.com

development: &development
  <<: *default

test:
  <<: *development

production:
  <<: *default

