require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExpeditionsController do

  # This should return the minimal set of attributes required to create a valid
  # Expedition. As you add validations to Expedition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExpeditionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all expeditions as @expeditions" do
      expedition = Expedition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:expeditions).should eq([expedition])
    end
  end

  describe "GET show" do
    it "assigns the requested expedition as @expedition" do
      expedition = Expedition.create! valid_attributes
      get :show, {:id => expedition.to_param}, valid_session
      assigns(:expedition).should eq(expedition)
    end
  end

  describe "GET new" do
    it "assigns a new expedition as @expedition" do
      get :new, {}, valid_session
      assigns(:expedition).should be_a_new(Expedition)
    end
  end

  describe "GET edit" do
    it "assigns the requested expedition as @expedition" do
      expedition = Expedition.create! valid_attributes
      get :edit, {:id => expedition.to_param}, valid_session
      assigns(:expedition).should eq(expedition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Expedition" do
        expect {
          post :create, {:expedition => valid_attributes}, valid_session
        }.to change(Expedition, :count).by(1)
      end

      it "assigns a newly created expedition as @expedition" do
        post :create, {:expedition => valid_attributes}, valid_session
        assigns(:expedition).should be_a(Expedition)
        assigns(:expedition).should be_persisted
      end

      it "redirects to the created expedition" do
        post :create, {:expedition => valid_attributes}, valid_session
        response.should redirect_to(Expedition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expedition as @expedition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expedition.any_instance.stub(:save).and_return(false)
        post :create, {:expedition => { "user" => "invalid value" }}, valid_session
        assigns(:expedition).should be_a_new(Expedition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expedition.any_instance.stub(:save).and_return(false)
        post :create, {:expedition => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested expedition" do
        expedition = Expedition.create! valid_attributes
        # Assuming there are no other expeditions in the database, this
        # specifies that the Expedition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Expedition.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => expedition.to_param, :expedition => { "user" => "" }}, valid_session
      end

      it "assigns the requested expedition as @expedition" do
        expedition = Expedition.create! valid_attributes
        put :update, {:id => expedition.to_param, :expedition => valid_attributes}, valid_session
        assigns(:expedition).should eq(expedition)
      end

      it "redirects to the expedition" do
        expedition = Expedition.create! valid_attributes
        put :update, {:id => expedition.to_param, :expedition => valid_attributes}, valid_session
        response.should redirect_to(expedition)
      end
    end

    describe "with invalid params" do
      it "assigns the expedition as @expedition" do
        expedition = Expedition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Expedition.any_instance.stub(:save).and_return(false)
        put :update, {:id => expedition.to_param, :expedition => { "user" => "invalid value" }}, valid_session
        assigns(:expedition).should eq(expedition)
      end

      it "re-renders the 'edit' template" do
        expedition = Expedition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Expedition.any_instance.stub(:save).and_return(false)
        put :update, {:id => expedition.to_param, :expedition => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested expedition" do
      expedition = Expedition.create! valid_attributes
      expect {
        delete :destroy, {:id => expedition.to_param}, valid_session
      }.to change(Expedition, :count).by(-1)
    end

    it "redirects to the expeditions list" do
      expedition = Expedition.create! valid_attributes
      delete :destroy, {:id => expedition.to_param}, valid_session
      response.should redirect_to(expeditions_url)
    end
  end

end
